version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./services/go/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./webproject:/usr/src/app
    command: air ./webproject/cmd/app/main.go -b 0.0.0.0
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webproject
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:

